<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Rincon.Utilities\Rincon.Utilities.csproj" />
	</ItemGroup>
  <ItemGroup>
    <Compile Remove="ArticleBatch.cs;CashRegisterSession.cs;Category.cs;Sale.cs;SaleDetail.cs;SaleDetailBatch.cs;SaleReturn.cs;SaleReturnDetail.cs;SaleReturnDetailBatch.cs;SaleExchange.cs;SaleExchangeBatch.cs" />
    <Compile Remove="ViewModels\ArticleVM.cs;ViewModels\CartItemVM.cs;ViewModels\CartVM.cs;ViewModels\CashRegisterVM.cs;ViewModels\ShoppingCartItemVM.cs;ViewModels\SalesIndexVM.cs;ViewModels\StatisticsVM.cs" />
  </ItemGroup>
</Project>
